# Generated by Django 3.1.5 on 2021-05-31 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auto_20210528_1733'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='active_auction',
            new_name='is_auction',
        ),
    ]
