# Generated by Django 3.1.5 on 2021-05-31 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auto_20210531_2205'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='is_auction',
            new_name='is_active',
        ),
    ]
