# Generated by Django 3.1.5 on 2021-06-02 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_auto_20210602_1924'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watchlist',
            old_name='User',
            new_name='user',
        ),
    ]
