# Generated by Django 3.1.5 on 2021-06-03 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_auto_20210602_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='product',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='auctions.product'),
        ),
    ]
