# Generated by Django 3.1.5 on 2021-06-03 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_auto_20210603_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='product',
            field=models.ManyToManyField(blank=True, related_name='auction_to_add', to='auctions.Product'),
        ),
    ]
