# Generated by Django 3.1.5 on 2021-06-06 15:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_auto_20210603_2248'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='watchers',
            field=models.ManyToManyField(blank=True, related_name='watched_listing', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Watchlist',
        ),
    ]
